### ISSUE TITLE
Observations & Comments

### ISSUE THREAD

**Issue by walmer-bolfet** [death2all110/yi-hack#17]
Good Morning from Alabama,

How is that “Filesystem has been set read-only” issue coming.  As I said yesterday, I reformatted my SD and got rid of it. This morning, after I edited some things on the SD card with my OS X computer, I got the “Filesystem has been set read-only” again.  Strange though, I restarted the camera without removing the SD card and it seems to have booted correctly.

More Observations/Comments:

Yesterday I mentioned there was nothing was showing at the “Records Files” page but “last_motion_check”.  Later in the day, I checked again, and the page seemed to be populated correctly with links to the saved files.    After rebooting this morning, the page no longer shows the links to saved files.  

In log_motion.txt files I am seeing 
 
Checking for motion at Fri Mar 31 10:25:10 CDT 2017...
{"armed": true, "motion": true, "last_motion_check": 1490973910, "host": "(none)"}
/home/hd1/test/check_motion.sh: line 25: /home/curl: not found
Motion file: 

It shows “motion”: true, but doesn’t record the Motion file name, even as the file is created and saved.
It also makes reference to checking line 25 in the script, but I can see anything wrong there.

Can you provide some information on the difference between these two scripts:
  1 /sd/test/scripts/copy_to_ftp.sh  and
  2 /sd/test/scripts/ftp_upload/ftp_upload.sh

I tried the ftp_upload.sh script and got error.  I think the common_lib.sh need to be updated with correct path to yi-hack.cfg file.
   DEFAULT_CONFIG_FILE="/home/hd1/test/**config**/yi-hack.cfg"
Still didn’t get it working but I can’t see any other error.  

Does it do anything more/different than copy_to_ftp.sh ?

Thanks again.

**Comment by death2all110** [comment]
Hello,

I just merged some changes.

The following PRs should resolve the issues.

https://github.com/death2all110/yi-hack/pull/18
https://github.com/death2all110/yi-hack/pull/19
https://github.com/death2all110/yi-hack/pull/20
https://github.com/death2all110/yi-hack/pull/21

Thanks.
