### ISSUE TITLE
China Camera

### ISSUE THREAD

**Issue by utya1988** [death2all110/yi-hack#22]
Hello. Can i use this hack on Chinese camera?

**Comment by death2all110** [comment]
You can try, but I make no guarantees of it working 100%. I'm not responsible should something happen and cause it to brick.

**Comment by utya1988** [comment]
Now i use https://github.com/fritz-smh/yi-hack, but i like dhcp config in your script.

**Comment by death2all110** [comment]
In that case, mine should work fine for you.
