### ISSUE TITLE
Too noise videos

### ISSUE THREAD

**Issue by zsoltacsai** [death2all110/yi-hack#26]
With this mod my cameras voice is too noise - but only this has only rtsp and cloud service.
With the original firmware everything was almost clear. Is there any option to fix this?
I have 4 cameras but all of them works like this.
FW: 1.8.7.0A_201702081101 (US version)

**Comment by death2all110** [comment]
This is not because of my mod, this is because of the newer firmwares from Yi. Only solution is to downgrade, which may break things with the hack
