### ISSUE TITLE
Timezone is off 8 hours when viewing from app

### ISSUE THREAD

**Issue by gl-lamhnguyen** [death2all110/yi-hack#27]
The clips from Activity Alerts work fine, but when I want to view the playback at a certain time, it wouldn't work until I scroll back 8 hours ago.

For example, if I want to view playback at 2 PM PDT, I have to scroll back to 6 AM, otherwise the playback would not show up and goes back to Live mode.

This is my config:

    TIMEZONE=PST8PDT,M3.2.0,M11.1.0
    NTP_SERVER=server 3.north-america.pool.ntp.org

**Comment by death2all110** [comment]
This is present even on my stock devices. Its a Firmware/App bug.
