### ISSUE TITLE
Not working on 1.8.7.0A_201702081101 ?

### ISSUE THREAD

**Issue by galadril** [death2all110/yi-hack#29]
I try to implement this hack to my Yi Home camera (international).
It boots up with the sd card, but it doesn't have al the features (h264, telnet, ftp, etc)

Im I doing something wrong?
- Write FAT32 SD card with content
- Config DHCP / Wifi settings
- Put the sd in Yi camera
- Reset camera
- But then it doesn't connect to wifi automaticly, i need to setup the connection via app??

Then camera works with the app, but not via the hack (http/ip/ not accessable)

I've also tried to install the hack in combination with another home file, all with the same results..
?

**Comment by galadril** [comment]
I don't have a ny Log.txt file under the test directory...

**Comment by joaoasilva** [comment]
It's working for me, the only thing that's not working is the Cloud services.

**Comment by galadril** [comment]
So your running the latest version of death2all110/yi-hack.
Any special things done to run it?

My cam is doing nothing after a reset, tried to downgrade, hack, whatever.. but nothing runs :)

**Comment by joaoasilva** [comment]
Yes, latest version, I configure the wireless on the wpa file and leave dhcp on and that's it.
I also format the sd card as recommended to always make sure the cam can access it on boot.

**Comment by galadril** [comment]
just like i did... really weird

**Comment by joaoasilva** [comment]
Did you try to clean the SD partitions?
Try this:
1 - Go to the windows start button, write diskpart and press "enter"

2 - Wait a few seconds and write on this order:
- "list disk" - shows you the disks that are currently connected to the computer;
- "select disk X" - substitute x with the number of the disk
- "clean" - deletes all the data in the SD (you may have to remove and reinsert the card after this step)
- "create partition primary" - creates a partition in the sd 
- "format quick" - makes a quick format

**Comment by galadril** [comment]
Thanks for the idea., but I've tried it without luck.
Still the same reaction, no hack loaded or anything.

**Comment by osmelmatos** [comment]
Doesn't work for me either :(. After the light stays solid blue for a second it goes back to blinking orange and nothing works.

**Comment by ghost** [comment]
Update: It does work. In my case I just had to make sure the config files were in the config folder. I was used to the older hack where the config files were in the root 👍

**Comment by chrisb22** [comment]
I having the same issue as galadrill. It seems like the camera is totally ignoring the sd card. It is a brand new card. I tried re-formatting several times. No dice on anything.

**Comment by ghost** [comment]
It's not the SD card. I tried from one of the working cameras and still the same message "waiting to connect". So far the two white cameras I bought work fine, and the two black cameras did not work. Maybe the black cameras have been "fixed".

**Comment by ghost** [comment]
Can anyone else confirm if they have white/black camera?

**Comment by chrisb22** [comment]
I have a black one that came from Amazon fulfilled  for Yi ordered on May 13

**Comment by galadril** [comment]
Mine is white

**Comment by hallveticapro** [comment]
Same issues here with two black units, just received today. Tried different versions of the hack, downgrading firmware, etc. Nothing seems to want to work. I just want to enable FTP access so I can have the video files pulled to my server.

**Comment by death2all110** [comment]
I'm wondering if these are different versions of the camera. Are these 1080p or 720p?

**Comment by hallveticapro** [comment]
720p for mine.

**Comment by galadril** [comment]
720 also

Op 18 mei 2017 11:53 p.m. schreef "adh1310" <notifications@github.com>:

**Comment by chrisb22** [comment]
720 for me too.

**Comment by michmike** [comment]
i am in the same boat.  i can't get this to work with 1.8.7. has anyone tried downgrading to an earlier firmware and see if that works?
http://xiaoyi.querex.be/firmwares/

**Comment by ghost** [comment]
@michmike I tried every single file. I wonder if they changed the way to downgrade in the latest firmware. Maybe a different file name instead of "home"?

**Comment by PDadsPalace** [comment]
So are we all in consensus that no one has it working on 1.8.7.0A_201702081101?  Or do the people at the top have it working?  With the App working as well?

**Comment by michmike** [comment]
i agree with the consensus that it is not working. i tried everything anyone posted in forums and i had no luck in getting this to work

**Comment by galadril** [comment]
not working indeed

**Comment by PDadsPalace** [comment]
Its such a perfect camera, if they didnt screw with it.  Well, if you guys figure anything out let me know.  I will do the same for you.  

All i want is to be able to view in TinyCam with all my exterior cams; but then use the YI app for talking and recording...

**Comment by ghost** [comment]
Just to make it clear... I have two hacked (white) cameras with firmware 1.8.7.0A_201702081101.
I bought two more, this time with the black base and can't install the hack. So yes, the hack works on this firmware but only on certain cameras. :(

**Comment by frakzz** [comment]
1.8.7.0A_201702081101 27US patch doesn't work

**Comment by PDadsPalace** [comment]
Just to confirm.  I too got it working on the latest firmware.  I have US white Version of camera.

**Comment by galadril** [comment]
@PDadsPalace you got it working?? HOW

**Comment by PDadsPalace** [comment]
Maybe I just got the right camera, like @0sm3l says he did.

What I did was bring the camera back to the stock firmware that it came with.  1.8.5 something.  I got it off the official site.

Then hooked up camera to wifi and app.  

Then did the SD card hack; and let the camera update on its own to the latest firmware.  Been up and running with RTSP, and the App is still working as well.  Been 2 days now.

**Comment by keith721** [comment]
Not working with my white US model YHS-113-IR, FCC ID 2AFIB-H150027A, QR code 27USYIBLWN  :(

May have found it! 8^D  Here's a snippet of the console output when I reset the camera with the SD card in:

    system startup
    =========1
    hello, open console
     do_auto_sd_update: detect flash size: 0x1000000, gsdexist=1 
    Interface:  MMC
      Device 0: Vendor: Man 035344 Snr 09d21606 Rev: 8.0 Prod: SS04G
                Type: Removable Hard Disk
                Capacity: 3781.5 MB = 3.6 GB (7744512 x 512)
    Partition 1: Filesystem: FAT32 "NO NAME    "
                system volume information/
        34816   log_init.tar.gz 
        36864   log_start_reset.tar.gz 
                test/
      7516872   home 
    
    3 file(s), 2 dir(s)
    
    
    1: log_init.tar.gz!
    2: log_start_reset.tar.gz!
    3: home!
    u-boot_y18 not found!
    env_y18 not found!
    conf_y18 not found!

It appears they might have appended '_y18' to the expected filenames?  It certainly appears so!

    System startup
    =========1
    hello, open console
    
     do_auto_sd_update: detect flash size: 0x1000000, gsdexist=1
    Interface:  MMC
      Device 0: Vendor: Man 035344 Snr 09d21606 Rev: 8.0 Prod: SS04G
                Type: Removable Hard Disk
                Capacity: 3781.5 MB = 3.6 GB (7744512 x 512)
    Partition 1: Filesystem: FAT32 "NO NAME    "
                system volume information/
      7971912   home_y18
    1 file(s), 1 dir(s)
    
    1: home_y18!
     find index 5: home_y18
    
    u-boot_y18 not found!
    env_y18 not found!
    conf_y18 not found!
    kernel_y18 not found!
    rootfs_y18 not found!
    reading home_y18
    
    magic 0x27051956 0x27051956
    arch 0x2 0x2
    size 0x79a408 0x40
    type 0x7 0x2
    crc 0x9ee3f490
    name 7518-hi3518-home
    idx5: old : 565d7bab, new : 565d7bab
    Image home_y18 is same time
    
     do_auto_update: detect flash size: 0x1000000
    ### UBOOT:test pin high! ###
    Hit any key to stop autoboot:  0
    16384 KiB hi_fmc at 0:0 is now current device

**Comment by hyptechdev2015** [comment]
Hi, I have version 1.8.7.0A_201702081101 USA, 720, the lastest @death2all110 's scripts  does work
however,  do not use function boot_voice(), I replace it with old code "/home/rmm"

Here is my update **equip_test.sh** that work for me @death2all110 

Please see it here:
http://codepaste.net/bv5ywo

**Comment by keith721** [comment]
@hyptechdev2015 Please consider creating a pull request and submitting your changes for inclusion in this GitHub repository.  Thanks!

**Comment by hyptechdev2015** [comment]
@keith721 @death2all110 

thank Keith, I created a new pull request. All other codes has no changes.

**Comment by PDadsPalace** [comment]
Today my RTSP feed seems to have stopped working.Cant seem to figure out why yet.

**Comment by PDadsPalace** [comment]
@hyptechdev2015 your updated code isn't found thru the link you provided.  Can you post it again?  My rtsp is down.  Is yours still working, because I see you say you are on the same firmware as me.

**Comment by PDadsPalace** [comment]
Why does my IP address keep changing?  It prevents me from using RTSP

**Comment by ghost** [comment]
@PDadsPalace set `DHCP=no` in `test/config/yi-hack.cfg`

**Comment by superm1** [comment]
Folks who did get this working w/ newer FW, can you please comment on the model number on the back of your camera?

I'm having problems with this working on my YHS-113-IR, but I notice that if I set it up with Android that the camera isn't even "detecting my SD card", so I'm not sure where to start (rename home to home_y18)?  Different SD card?

**Comment by patosullivan** [comment]
I'm having the same issue. Model: YHS-113-IR, white.

@hyptechdev2015's idea to replace boot_voice with /home/rmm did not work either.

**Comment by death2all110** [comment]
It seems those that are having issues here may have a newer version of the camera. I have the 22US version of YHS-113-IR White and it works fine. the first 4 characters of the # below the QR code will tell you what version. I have no way of testing 27US.

For 27US, I recommend [shadow-1/yi-hack-v3](https://github.com/shadow-1/yi-hack-v3)

If you're using 22US and having issues, I can attempt to help.
