### ISSUE TITLE
Working fine with CN fw 1.8.7.0C_201705091058

### ISSUE THREAD

**Issue by coax** [death2all110/yi-hack#32]
Not an issue but feedback:

I have first version Yi Home camera for Chinese market (bought on AliExpress in 11/2015) with latest firmware 1.8.7.0C_201705091058 installed.

Placed the hack on SD card 64gb (FAT32), configured scripts for wifi and settings, replaced the "home" that comes with hack with latest firmware file from http://www.xiaoyi.com/home/firmware/download/?version=1 (renamed to home), put the card in and it works without issues.

Thanks to author(s) of this hack.

**Comment by farhanito** [comment]
just tried it with the same firmware, and got that "this camera can only be used within china" message :(

any idea how to overcome that?

EDIT:
fixed by using "hack_yi.sh" and "cloudAPI" from here https://diy.2pmc.net/solved-xiaomi-xiao-yi-ant-home-camera-can-used-china/
---with some editing

**Comment by notdone** [comment]
And how about CN fw 1.8.6.1B2 (mod fw on 1.8.6.1B)? Can use?

**Comment by death2all110** [comment]
I'm using the international camera, so I have no way to support or try the chinese firmware.
