### ISSUE TITLE
Remove CTRL-M characters / ^M from ftp_upload.sh housekeeper.sh

### ISSUE THREAD

**Issue by hyptechdev2015** [death2all110/yi-hack#34]
_This is not an issue, it's a solution._

One might experience ^M return line while transfer file from dos to unix

use this command to return ^M every end of line

**From Telnet:**

```
#dos2unix /home/hd1/test/scripts/ftp_upload/common_lib.sh

#dos2unix /home/hd1/test/scripts/ftp_upload/ftp_upload.sh

#dos2unix /home/hd1/test/scripts/housekeeper/housekeeper.sh
```

**Comment by death2all110** [comment]
Updated Readme.

Fixed #40
