### ISSUE TITLE
can not view rtsp stream

### ISSUE THREAD

**Issue by thienedits** [death2all110/yi-hack#4]
Hello I flashed your hack on my US model of the camera. Everything seems to be working as I can view the stream on the official Yi android app and the page loads in my browser when I go to the camera's ip address. However when I try loading the rtsp stream in vlc it will not connect.

**Comment by thienedits** [comment]
I got it working, it was an issue the network configs in the yi-hack.cfg file.

**Comment by death2all110** [comment]
@thienedits glad you got it working!
