### ISSUE TITLE
Disable automatic housekeeping of recordings on SD card by firmware

### ISSUE THREAD

**Issue by gaarder** [death2all110/yi-hack#6]
Here's the hardware information of my Yi Camera:

Hardware version informations :
    hwplatform=2
Software version informations :
    [sys]
    version=1.8.6.1B_201604071154
    [kernel]
    version=3-0.8
    provider=1
    devtype=1
Firmware letter is : 'B'

The camera is disconnected from the network, i.e. connected to a wifi router that provides only a LAN connection on wifi (but is able to synchronize with internet clock through a 3.5G USB stick).

It seems that the camera firmware itself (the binary files mp4record or something else) will cleanup camera recordings automatically after 3 days, even when /dev/hd1 is only half full. The cleanup seems to happen daily at 6am. This renders the delete_old_videos.sh cron task useless.

Does anyone know how to disable this automatic housekeeping by the camera itself?

**Comment by death2all110** [comment]
I have not noticed this myself, but I will keep my eyes peeled. My dev device is usually turned off when I'm done messing with it. I'll leave it on for a few days and report back.
