### ISSUE TITLE
Is the recorded timeline within the App working?

### ISSUE THREAD

**Issue by lolento** [death2all110/yi-hack#7]
Hello, so I got rtsp and the app working.  I can see alerts and the short alert video via the app as well as live feed via RTSP or the app.

But the timeline of recorded video isn't working for me?  Is this suppose to be working?

**Comment by death2all110** [comment]
I believe the timeline issue is a bug with the app. As i have the same issue, even on my stock cameras. Hopefully I can come up with a fix at some point, but in the meantime I will be closing this as its not a issue with this custom firmware.
